name: Development Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-and-test-main:
    name: Build and Test
    uses: ./.github/workflows/build-test.yml
    with:
      ubuntu_version: "22.04"
      build_type: Debug
  static-analysis:
    name: Static Analysis
    uses: ./.github/workflows/static-analysis.yml
  pre-commit:
    name: Pre-Commit Checks
    uses: ./.github/workflows/pre-commit.yml
