name: Build & Test

on:
  workflow_call:
    inputs:
      ubuntu_version:
        required: true
        type: string
      build_type:
        required: true
        type: string

jobs:
  build-and-test:
    name: ${{ inputs.build_type }} Build & Test
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    steps:
      - uses: actions/checkout@v3

      - name: Check deps versions
        uses: devcontainers/ci@v0.3
        env:
          UBUNTU_VERSION: ${{ inputs.ubuntu_version }}
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer:${{ inputs.ubuntu_version }}
          runCmd: |
            cmake --version
            ctest --version
            g++ --version

      - name: Build
        uses: devcontainers/ci@v0.3
        env:
          UBUNTU_VERSION: ${{ inputs.ubuntu_version }}
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer:${{ inputs.ubuntu_version }}
          runCmd: |
            cmake -B build/ -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}
            cmake --build build/ -j

      - name: Run tests
        uses: devcontainers/ci@v0.3
        env:
          UBUNTU_VERSION: ${{ inputs.ubuntu_version }}
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer:${{ inputs.ubuntu_version }}
          runCmd: |
            ctest --test-dir ./build/ --output-on-failure -T Test
