name: Full Build & Test Suite

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-and-test-full:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        build_type: [Debug, Release]
    name: ${{ matrix.os }} ${{ matrix.build_type }} Build & Test
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y cmake lcov
      - name: Check deps versions
        run: |
          cmake --version
          ctest --version
          g++ --version
      - name: Build
        run: |
          cmake -B build/ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build/ -j2
      - name: Run tests
        working-directory: build
        run: |
          ctest --output-on-failure -T Test
