name: Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  debug-build-and-test:
    name: Debug Build & Test ${{ matrix.cxx }}
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        cc: ["gcc-11"]
        cxx: ["g++-11"]
        include:
          - os: "ubuntu-22.04"
            cc: "clang-14"
            cxx: "clang++-14"

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt install -y lcov

      - name: Build
        run: scripts/build-debug.sh

      # script builds, runs tests, and generates coverage info
      - name: Generate test coverage
        if: ${{ !contains(matrix.cxx, 'clang') }}
        run: bash scripts/run-coverage.sh

      - name: Upload coverage to Coveralls
        if: ${{ !contains(matrix.cxx, 'clang') }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./build/lcov.info
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true
          debug: true


  release-build-test:
    name: Relase Build & Test ${{ matrix.cxx }}
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        cc: ["gcc-11"]
        cxx: ["g++-11"]
        include:
          - os: "ubuntu-22.04"
            cc: "clang-14"
            cxx: "clang++-14"

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: bash scripts/build-release.sh

      - name: Test
        run: ctest --test-dir ./build/ --output-on-failure -T Test

  finish:
    needs: debug-build-and-test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        parallel-finished: true
