name: Test Suite

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        build_type: [Debug, Release]
    name: ${{ matrix.build_type }} Build & Test
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y cmake
      - name: Check deps versions
        run: |
          cmake --version
          ctest --version
          g++ --version
      - name: Build
        run: |
          cmake -B build/ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build/ -j2
      - name: Run tests
        working-directory: build
        run: |
          ctest --output-on-failure
