name: Full Build & Test Suite

on:
  pull_request:
    branches: ["release"]

  workflow_dispatch:

jobs:
  build-and-test-full:
    strategy:
      matrix:
        ubuntu_version: ["20.04", "22.04"]
        build_type: [Debug, Release]
    uses: ./.github/workflows/build-test.yml
    with:
      ubuntu_version: ${{ matrix.ubuntu_version }}
      build_type: ${{ matrix.build_type }}
