name: Doxygen

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  doxygen-site:
    name: Doxygen
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, '[ci skip]') }}"

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt install -y doxygen graphviz

      - name: Generate docs
        run: |
          bash ./scripts/gen-doxygen.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/html/