# cppcheck static analysis
name: Static Analysis

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v3
      - name: Install cppcheck
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y cppcheck

      - name: Check cppcheck version
        run: cppcheck --version

      - name: Get file list
        run: |
          find ./src ./include \
          -type f \( -iname *.cpp -o -iname *.h \) > files.txt

      - name: Run cppcheck
        run: |
          cppcheck --file-list=./files.txt \
            --quiet \
            --enable=style,warning \
            --language=c++ \
            --std=c++20 \
            --platform=unix64 \
            -I ./include/ \
            -i ./build/ \
            -i ./test/
