name: Static Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  static-analysys:
    name: Static Analysis
    runs-on: ubuntu-22.04
    if: "${{ !contains(github.event.head_commit.message, '[ci skip]') }}"

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          git clone --branch 2.17.1 https://github.com/danmar/cppcheck.git
          cmake -S cppcheck/ -B cppcheck/build/
          cmake --build cppcheck/build -j2
          sudo cmake --install cppcheck/build

      - name: CMake compile commands
        run: bash scripts/build-debug.sh

      - name: CppCheck
        run: bash scripts/run-cppcheck.sh

      # - name: clang-tidy
      #   run: bash scripts/run-clang-tidy.sh
