name: Static Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  static-analysis:
    name: CppCheck Static Analysis
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    steps:
      - uses: actions/checkout@v3

      - name: Check cppcheck version
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer:22.04
          runCmd: cppcheck --version

      - name: Run cppcheck
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer:22.04
          runCmd: bash scripts/run-cppcheck.sh
