# cppcheck static analysis
name: Static Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v3
      - name: Install cppcheck
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y cppcheck

      - name: Check cppcheck version
        run: cppcheck --version

      - name: Run cppcheck
        run: bash scripts/run-cppcheck.sh
